# conventional commit types: https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json
# https://www.conventionalcommits.org/en/v1.0.0-beta.2/#commit-message-for-a-fix-using-an-optional-issue-number
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - improv

# Always validate the PR title
# and ignore the commits to lower the entry bar for contribution
# while titles make up the Release notes to ease maintenance overhead
titleOnly: true
